---
version: 2
gousto_build_image: &gousto_build_image
- image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/php56:latest
  aws_auth:
    aws_access_key_id: $AWS_ERC_ACCESS_KEY
    aws_secret_access_key: $AWS_ERC_SECRET_KEY
jobs:
  test:
    docker: *gousto_build_image
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: composer install --prefer-dist --no-interaction -o
    - run:
        name: Run tests
        command: ./vendor/bin/codecept run --coverage --coverage-xml --coverage-html

workflows:
  version: 2
  pull-request-branch:
    jobs:
    - test:
        context: gousto-beta-aws-app-circleci
